Page catalog filter
AntonBox/django_shop pull request #11
Opened 2016-12-14 00:54 UTC by AntonBox

2016-12-24 11:44 UTC, AndrewPix requested changes

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/models.py
> +    def __unicode__(self):
что за фигня?) ты в каком питоне работаешь? это для версии 2. мы работаем в 3.5 и нужно писать `__str__` метод для Создания кастомной строковой репрезентации обьекта класса.

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/models.py
> -        verbose_name_plural = 'Categories'
зачем это убрал? джанго по-умолчанию добавляет к названию модели просто s, в админке, и для категорий получается category. Поэтому  в таких случаях мы прописываем это явно.

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/models.py
> +        return ('view_category_url', None, {'slug': self.slug})
если у тебя нету позиционных аргументов то не нужно передавать None. И вообще permalink неофициально считается deprecated. лучше юзать reverse(). Так что замени

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/models.py
>      image = models.ImageField(upload_to='static/img')
во-первых зачем указывать префикс статик если загрузка будет всеравно в mediafiles. во-вторых лучше тут заюзать функцию для определения пути. в офф доках есть инфа для этого. сделай что путь был типа products/*дата загрузки*/

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/models.py
>      image = models.ImageField(upload_to='static/img')
для category укажи related name

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/models.py
> +    def __unicode__(self):
это вернуть аналогично как ввыше

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/urls.py
> +    url(r'^category/(?P<slug>[^\.]+).html',
- зачем .html ?)
- в конце обязательно должен быть символ окончания паттерна $ (почитай http://stackoverflow.com/questions/31056789/difference-between-and-in-urls-django)
- лушч еиспользовать такой regex - (?P<slug>[-\w]+)

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/urls.py
> +        view_category, name='view_category_url'),
в имени юрл паттерна не нужно писать что это url, тут достаточно написать view_category

2016-12-24 11:44 UTC, AndrewPix commented on templates/catalog.html
> +	{% else %}
у django есть тег empty для такого. так что не нужно делать лишние проверки сразу пиши цикл for, а потом empty

2016-12-24 11:44 UTC, AndrewPix commented on templates/catalog.html
> +	{% if products %}
тут аналогично, убери проверку эту

2016-12-24 11:44 UTC, AndrewPix commented on templates/products.html
> +
я так понимаю этот шаблон не используется? тогда убери его

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/views.py
> +    return render_to_response('catalog.html', {
используй render функцию везде

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/views.py
> +def view_category(request, slug):
я бы лучше написал одну вьюху вместо этих двух - `def products(request, slug=None):`
написание slug=None делает его опциональным, дальше направляешь оба урла на эту одну вьюху а уже во вьюхе смотришь если слаг был предоставлен, берешь категорию и фильтруешь по ней, если нет то отдаешь все продукты.

2016-12-24 11:44 UTC, AndrewPix commented on apps/catalog/urls.py
> +from apps.catalog.views import catalog, view_category
лучше просто импортнуть `from apps.catalog import views as catalog_views` что бы не импортировать каждый раз новые функции.

2016-12-24 11:44 UTC, AndrewPix commented on static/js/prod.filter.js
> +$(document).ready(function(){
этот код лучше удали из памяти) и отсюда тоже)

2016-12-28 19:23 UTC, AntonBox commented on apps/catalog/views.py
> +def view_category(request, slug):
да, это норм

2016-12-28 19:23 UTC, AntonBox commented on static/js/prod.filter.js
> +$(document).ready(function(){
мы не будем джейквери использовать?

2017-01-04 09:58 UTC, AndrewPix commented on static/js/prod.filter.js
> +$(document).ready(function(){
будем, но конкретно эти скрипты не нужны

2017-01-05 09:19 UTC, AndrewPix requested changes

2017-01-05 09:19 UTC, AndrewPix commented on apps/catalog/models.py
> +    image = models.ImageField(upload_to='static/img')
Так что с путями для изображений? Нужно сделать динамические как я уже говорил. пример:
```
def get_institution_image_path(instance, filename):
    return 'institutions/{}/images/{}'.format(instance.institution.uuid.hex, filename)

image = models.ImageField(upload_to=get_institution_image_path)
```

https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.FileField.upload_to

2017-01-05 09:19 UTC, AndrewPix commented on apps/catalog/models.py
> +    category = models.ForeignKey(Category, related_name='categories',)
related name это имя обьектов этой модели по которому их vожно будет получить с модели на котороую ссылается это поле.
т.е. для модели Category, эти обьекты проавильно назвать products. и тогда можно будет с какого-нибудь инстанса категории сделать так: `category.products.all()`

2017-01-05 09:19 UTC, AndrewPix commented on apps/catalog/views.py
> +def products(request, slug=None):
уже лучше, но все ещё много лишнего кода. ты должен следовать принципу DRY - http://www.stijit.com/web-tips/dry-kiss-solid-yagni

в первую очередь проверить слаг можно проще - `if slug:`
дальше сделай только один return, в котором уже один раз будешь брать все категории. а в операторе if, else уже бери продукцию в зависимости от наличия слага.

2017-01-06 09:12 UTC, AndrewPix requested changes

2017-01-06 09:12 UTC, AndrewPix commented on apps/catalog/views.py
> +        products = Product.objects.filter(category=category)
Почитай про django querysets, про то как они выполняются. тут правильней будет отфильтровать первый query. т.е. напсать `products = products.filter(category=category)`

2017-01-06 09:12 UTC, AndrewPix commented on apps/catalog/models.py
> +    category = models.ForeignKey(Category, related_name='products',)
запятая в конце лишняя

2017-01-06 09:12 UTC, AndrewPix commented on apps/catalog/models.py
> +    def get_image_path(instance, filename):
это должна быть отдельная функция а не метод класса.

2017-01-06 09:12 UTC, AndrewPix commented on apps/catalog/models.py
> +    image = models.ImageField(upload_to='img')
тут тогда лучше указать папку с названием `categories`

2017-01-06 22:27 UTC, AndrewPix approved these changes

2017-01-06 22:27 UTC, merged