Page order
AntonBox/django_shop pull request #17
Opened 2017-02-07 19:28 UTC by AntonBox

на страничке ордер отображается полная стоимостьь всех товаров и запрашивается адресс и телефон пользователя. после чего даные отправляются, создаётся order, а корзина закрывается.

2017-02-11 17:12 UTC, AndrewPix commented on templates/order.html
> +		<h1>Error total</h1>
убрать

2017-03-05 19:40 UTC, AndrewPix requested changes

2017-03-05 19:40 UTC, AndrewPix commented on apps/order/views.py
> +        order = Order(user=user, cart=cart, phone=phone, adress=adress)
переделать на форму

2017-03-05 19:40 UTC, AndrewPix commented on apps/order/models.py
> +    adress = models.CharField(max_length=255)
верни назад

2017-03-05 19:40 UTC, AndrewPix commented on apps/order/views.py
> +    for item in cart_items:
сделать это методом в модели Cart

2017-03-05 19:40 UTC, AndrewPix commented on static/js/add-cart.js
> +    phone = document.getElementById(phone).value;
переделать на формы, и в пост просто передавать значения формы(почитай как взять все значения формы)

2017-03-05 19:40 UTC, AndrewPix commented on templates/cart.html
> +			<button>GO TO DEAL</button>
ссылка ?

2017-03-05 19:40 UTC, AndrewPix commented on templates/order.html
> +<script type="text/javascript"src="{% static "js/add-cart.js" %}"></script>
убрать, это подколючается в base

2017-03-06 12:43 UTC, AndrewPix commented
и исправь конфликты

2017-03-10 07:44 UTC, AndrewPix commented on apps/cart/models.py
> +    def get_user_cart_or_404(user):
убери or_404, все таки это лишнее, у нас в любом случае корзина будет после метода get_or_create
и сделай это классметодом(почитай что это)

2017-03-10 07:45 UTC, AndrewPix commented on apps/cart/models.py
> +    def get_user_cart_or_404(user):
А вообще лучше сделай это методом юзера

2017-03-14 22:07 UTC, AndrewPix requested changes

2017-03-14 22:07 UTC, AndrewPix commented on apps/order/views.py
> +        cart.status = 'Closed'
closed вообще-то, но ещё правильней использовать константы - Cart.CLOSED

2017-03-14 22:07 UTC, AndrewPix commented on apps/catalog/models.py
> +    detail = models.SlugField(max_length=255)
почему это названо так? почему не slug?

2017-03-14 22:07 UTC, AndrewPix commented on apps/catalog/views.py
> +def product_detail(request, detail):
details

2017-03-14 22:07 UTC, AndrewPix commented on apps/order/migrations/0004_auto_20170306_0000.py
> +    ]
куча миграций, причем не самых полезных) сделай squash для них. что бы была всего одна в этом app, и мб посмотри ещё в других

2017-03-14 22:07 UTC, AndrewPix commented on apps/order/views.py
> +        return redirect('/deal/')
Что тут вообще происходит не понял?) ты редиректишь на вьюху просто что бы показать темплейт который нужен только тут? отрендерь его тут, а ту вьюху вообще удали, тем более из core

2017-03-14 22:07 UTC, AndrewPix commented on templates/cart.html
> +			<button>GO TO DEAL</button>
Что делает этот button? может тут лучше link, со ссылкой на ордер?

2017-03-14 22:07 UTC, AndrewPix commented on templates/detail.html
> +		<p>Sorry, there no product like this</p>
такой ситуации не может быть. у тебя должен во вьюхе продукт братся get_object_or_404, и если его не будет то вернётся ошибка 404.

2017-03-14 22:07 UTC, AndrewPix commented on templates/order.html
> +	{% if total %}
убери все эти проверки иф. тотал всегда должен быть,

2017-03-14 22:07 UTC, AndrewPix commented on templates/order.html
> +	<form action="/order/confirm/" method="post">
используй template tag - url https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#url, чтобы реверсить урлы по имени, так нужно делать везде на фронте

2017-03-14 22:07 UTC, AndrewPix commented on templates/order.html
> +{% block extra_script %}
этот блок совсем тут не нужен. load staticfiles просто грузит темлейт тег для того что бы пписать static тег)

2017-03-14 22:07 UTC, AndrewPix commented on templates/order.html
> +{% load staticfiles %}
убери

2017-03-14 22:07 UTC, AndrewPix commented on templates/order.html
> +
тут как-то много места, если нужны отступы то на крайний случай напиши эти br уже хоть вместе. а вообще такое стилями делается

2017-03-14 22:07 UTC, AndrewPix commented on templates/detail.html
> +			<h4><a href="{{ product.get_absolute_url }}">{{product.name}}</h4></a>
а куда будет вести эта ссылка?

2017-03-14 22:07 UTC, AndrewPix commented on templates/confirm.html
> +<h3>Your order processing wait for our call</h3>
Your order is processing, wait for our call.

2017-03-14 22:07 UTC, AndrewPix commented on apps/order/views.py
> +        return HttpResponse({'message': 'Incorrect address or phone, or both!'}, status=400)
если форма не валидная то нужно вернуть форму с ошибками и показать их.

2017-03-14 22:07 UTC, AndrewPix commented on apps/order/models.py
> +    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
лучше не CASCADE а SET_NULL, что бы если мы почистим старые корзины, ордер оставался

2017-03-15 11:31 UTC, AntonBox commented on apps/catalog/models.py
> +    detail = models.SlugField(max_length=255)
я видел так делают, решил так сделать. это принципиально?

2017-03-15 12:33 UTC, AndrewPix commented on apps/catalog/models.py
> +    detail = models.SlugField(max_length=255)
ну у тебя в модели Category называется slug, тут уже по другому

2017-03-16 23:16 UTC, AndrewPix approved these changes

2017-03-16 23:16 UTC, merged