Create models
AntonBox/django_shop pull request #3
Opened 2016-11-02 05:36 UTC by Yondex

2016-11-09 12:13 UTC, AntonBox commented
everything ok

2016-11-10 09:25 UTC, AndrewPix requested changes
Убери базу данных sqlite из проекта, и добавь её в gitignore

2016-11-10 09:25 UTC, AndrewPix commented on root/settings.py
> +    'apps.Catalog',
Название django apps должно быть lowercase - rock_n_roll например.

2016-11-10 09:25 UTC, AndrewPix commented on root/settings.py
> +DEBUG = True
Это нельзя менять тут. Включать режим дебаггинга нужно в local_settings.py

2016-11-10 09:25 UTC, AndrewPix commented on apps/Cart/models.py
> +    status = models.CharField(max_length = 6, choices = status_choice, default = 'Closed')
передавать значения параметров нужно без пробелов - `max_length=6`

2016-11-10 09:25 UTC, AndrewPix commented on apps/Cart/models.py
> +    status_choice = ( (OPEN, 'Open'), (CLOSED, 'Closed') )
Убери пробелы после открытия и перед закрытием скобок кортежа

2016-11-10 09:25 UTC, AndrewPix commented on apps/Cart/models.py
> +    status = models.CharField(max_length = 6, choices = status_choice, default = 'Closed')
Поправь это везде

2016-11-12 09:55 UTC, AndrewPix requested changes

2016-11-12 09:55 UTC, AndrewPix commented on apps/cart/models.py
> +class User(TimedModel):
Мы пока не будем создавать кастомную модель юзера, используюй стандартную
https://docs.djangoproject.com/en/1.10/ref/contrib/auth/

2016-11-12 09:55 UTC, AndrewPix commented on apps/catalog/models.py
> +class Category(TimedModel):
Добавь `verbose_name_plural` в мета класс чтобы указать джанго правильную форму названия для этой модели в множестенном числе

2016-11-12 09:55 UTC, AndrewPix commented on apps/catalog/admin.py
> +admin.site.register(Category)
Укажи поля которые будут отображаться в админке при просмотре list view
https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display

2016-11-12 09:55 UTC, AndrewPix commented on apps/catalog/models.py
> +    name = models.CharField(max_length=30)
не нужно ставить жесткие ограничение если это реально не нужно. Ставь 255 для charfield

2016-11-12 09:55 UTC, AndrewPix commented on apps/catalog/models.py
> +    name = models.CharField(max_length=30)
Проверь это везде

2016-11-13 17:38 UTC, AndrewPix requested changes

2016-11-13 17:38 UTC, AndrewPix commented on apps/catalog/admin.py
> +    list_display = ('name', 'price','description')
после 'price' пробел пропустил

2016-11-13 17:38 UTC, AndrewPix commented on root/settings.py
> +    'suit',
Что это?

2016-11-13 17:38 UTC, AndrewPix commented on apps/cart/migrations/0002_auto_20161113_0303.py
> +        migrations.DeleteModel(
миграции нужно удалить и заново сгенерировать что бы не было бессмысленных созданий и удалений.

2016-11-13 17:40 UTC, AndrewPix commented on apps/catalog/models.py
> +        verbose_name_plural = ('categories')
Это должна быть просто строка а не кортеж. И с заглавной буквы.

2016-11-14 04:31 UTC, Yondex commented on root/settings.py
> +    'suit',
это другая тема админки Django(http://djangosuit.com/) - убрал из settings.py

2016-11-14 09:53 UTC, AndrewPix requested changes

2016-11-14 09:53 UTC, AndrewPix commented on apps/cart/models.py
> +    status = models.CharField(max_length=6, choices=status_choice, default='Closed')
`OPEN = 'Open'` - тут лучше присваивать lowercase значения а в кортеже status_choice уже с заглавной. В кортеже ты прописываешь как бы label к этим занчениям.

default должно ссылаться на переменную CLOSED

2016-11-14 09:53 UTC, AndrewPix commented on apps/cart/admin.py
> +admin.site.register(CartItem)
этим моделям тоже попрописывай list_display

2016-11-14 09:53 UTC, AndrewPix commented on apps/catalog/models.py
> +        verbose_name_plural='Categories'
Тут уже не параметр а просто присваивание, т.е. должны быть пробелы вокруг знака =

2016-11-14 09:53 UTC, AndrewPix commented on apps/catalog/models.py
> +    class Meta:
перед классом должна быть пустая строка. Ты юзаешь плагин какой-то для проверки PEP ?

2016-11-14 10:02 UTC, AndrewPix commented on root/settings.py
> +    'suit',
ну нам пока стандартной хватит. Нельзя так просто добавлять что-то в INSTALLED_APPS, не прописав это в requirements.txt

2016-11-14 11:13 UTC, Yondex commented on apps/catalog/models.py
> +    class Meta:
Уже поставил, спасибо за совет) проверил все файлы по стандарту pep8 и исправил кроме файлов миграции.

2016-11-14 11:59 UTC, AndrewPix approved these changes

2016-11-14 12:01 UTC, merged