model Order
AntonBox/django_shop pull request #5
Opened 2016-11-11 11:29 UTC by AntonBox

2016-11-12 09:57 UTC, AndrewPix requested changes

2016-11-12 09:57 UTC, AndrewPix commented on apps/Order/admin.py
> +# Register your models here.
Убери коммент

2016-11-12 09:57 UTC, AndrewPix commented on apps/Order/admin.py
> +# Register your models here.
Укажи поля которые будут отображаться в админке при просмотре list view
https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display

2016-11-12 09:57 UTC, AndrewPix commented on apps/Order/models.py
> +    phone = models.CharField(max_length=13)
Для телефона сделай лучше 20, для адреса 255

2016-11-12 09:57 UTC, AndrewPix commented on root/settings.py
> +    'apps.Order'
все django apps должны быть lowercase

2016-11-13 17:43 UTC, AndrewPix requested changes

2016-11-13 17:43 UTC, AndrewPix commented on apps/Order/apps.py
> +    name = 'Order'
lowercase для пути и для названия

2016-11-13 17:43 UTC, AndrewPix commented on apps/Order/migrations/0001_initial.py
> +                ('phone', models.CharField(max_length=13)),
нужно заново сгенерировать миграции, после того как ты изменил в модели.

2016-11-13 17:43 UTC, AndrewPix commented on apps/Order/views.py
> +# Create your views here.
убрать коммент

2016-11-13 17:43 UTC, AndrewPix commented on apps/order/models.py
> +    # user = models.ForeignKey(User, on_delete=models.CASCADE)
тут давай пока ссылатся на стандартную User модель в джанго

2016-11-13 20:45 UTC, AntonBox commented on apps/order/models.py
> +    # user = models.ForeignKey(User, on_delete=models.CASCADE)
всмысле ссылаться? убрать коммент и поставить ФК на User из django.contrib.auth.models?

2016-11-13 20:45 UTC, AntonBox commented on apps/Order/views.py
> +# Create your views here.
я вообще этот файл убрал. по тупости он сюда попал, его не должно здесь быть

2016-11-13 20:47 UTC, AntonBox commented on apps/Order/migrations/0001_initial.py
> +                ('phone', models.CharField(max_length=13)),
это со старого коммита

2016-11-13 20:47 UTC, AntonBox commented on apps/Order/apps.py
> +    name = 'Order'
как это попало? это старый коммит

2016-11-14 09:54 UTC, AndrewPix commented on apps/order/models.py
> +    # user = models.ForeignKey(User, on_delete=models.CASCADE)
да

2016-11-14 11:07 UTC, AndrewPix approved these changes

2016-11-16 19:22 UTC, merged